display detail console based on the condition
pea3nut/timeline pull request #8
Opened 2022-05-20 03:46 UTC by ganganiSoN

- Maintain the variable for handling the conflict and display the conflict data.

2022-05-20 06:47 UTC, pea3nut requested changes
- Other than comments, try to improve the semantic and format as well
- Add more information in your PR. E.g a screenshots and more descritions

2022-05-20 06:47 UTC, pea3nut commented on src/extensions/ConflictFixer/index.ts
> +                filterData = filterData.filter((v, i, arr) => arr.indexOf(v) === i);
What's the purpose of this?

2022-05-20 06:47 UTC, pea3nut commented on src/extensions/index.ts
> +    conflicts: {event_body: Conflict<EventBody>[]} = {event_body: []};
This exporting object is for all extensions. But the property you added is only for ConflictFixers, so you cannot add here

2022-05-20 06:47 UTC, pea3nut commented on src/extensions/index.ts
> +        // holds the conflicts which are occurs during the timeline creation
Use jsdoc format

2022-05-20 06:47 UTC, pea3nut commented on src/extensions/ConflictFixer/index.ts
> +                let x = `%cAn error was received:`;
Try to use more readable name for every varibles

2022-05-20 06:47 UTC, pea3nut commented on src/extensions/ConflictFixer/index.ts
> +                    if (!dateDiff.sort().reverse()[0]) {
Always create a readable variable for such complex condition

2022-05-20 06:47 UTC, pea3nut commented on src/extensions/ConflictFixer/EventBody2EventBodyFloater.ts
> +            this.ext.conflicts.event_body = this.conflicts.map(v => v);
Use `Array.from` instead

2022-05-20 06:47 UTC, pea3nut commented on src/extensions/ConflictFixer/index.ts
> +                    return this.ext.conflicts.event_body.forEach(eb => {
Why `return`?

2022-05-20 06:47 UTC, pea3nut commented on src/extensions/ConflictFixer/index.ts
> +                            filterData.push(JSON.stringify(ud));
In this scenario, the best semantic method is `.map`

2022-05-20 06:47 UTC, pea3nut commented on src/extensions/ConflictFixer/index.ts
> +                console.log(x, 'color: #D0342C; font-size: 16px;', 'color: #D0342C; font-size: 16px;', 'color: #F6E7D8; font-size: 16px; border: 1px groove  #F5F5F5; padding: 4px;');
How about `.warn` or `.error`

2022-05-20 06:47 UTC, pea3nut commented on src/extensions/ConflictFixer/index.ts
> +                console.log(x, 'color: #D0342C; font-size: 16px;', 'color: #D0342C; font-size: 16px;', 'color: #F6E7D8; font-size: 16px; border: 1px groove  #F5F5F5; padding: 4px;');
It's not a good idea that printing logs at several place. Try to merge the code about printing logs into L94

2022-05-20 08:01 UTC, ganganiSoN commented on src/extensions/ConflictFixer/index.ts
> +                filterData = filterData.filter((v, i, arr) => arr.indexOf(v) === i);
Finding Unique value from the Array.

2022-05-21 13:00 UTC, ganganiSoN commented
With Correct Data:

Input: [
    {
        date: '2012-12-28',
        endDate: '2012-12-27',
        title: 'Event 1',
        description: 'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'
    },
    {
        date: '2012-12-2',
        endDate: '2014-3-9',
        title: 'Event 1',
        description: 'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'
    },
]

![image](https://user-images.githubusercontent.com/33144041/169652381-1e8906e4-9b93-48ee-9e80-b46da1c1ba1b.png)

With Wrong Data:

Input: [
    {
        date: '2012-12-28',
        endDate: '2012-12-27',
        title: 'Event 1',
        description: 'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'
    },
    {
        date: '2012-12-28',
        endDate: '2014-3-9',
        title: 'Event 1',
        description: 'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'
    },
];

![image](https://user-images.githubusercontent.com/33144041/169652444-987a41ce-4095-40d1-8e74-2d1409c35dcd.png)

Input: [
    {
        date: '2012-12-28',
        endDate: '2012-12-27',
        title: 'Event 1',
        description: 'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially.'
    },
    {
        date: '2012-12-27',
        endDate: '2014-3-9',
        title: 'Event 1',
        description: 'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially.'
    },
    {
        date: '2012-12-26',
        title: 'Event 3',
        // description: 'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially.'
    }
];

![image](https://user-images.githubusercontent.com/33144041/169652509-8f4be566-424a-44e0-857e-224c373571bd.png)

2022-05-28 04:01 UTC, pea3nut commented on src/extensions/ConflictFixer/EventBody2EventBodyFloater.ts
> +        const conflictFixer = this.ext.extensions.filter(v => v instanceof ConflictFixer)[0] as ConflictFixer;
`this.ext.extensions.find(v => v instanceof ConflictFixer)`

2022-05-28 04:01 UTC, pea3nut commented on src/extensions/ConflictFixer/index.ts
> +                    errorMsg = `${errorMsg} “Too many long text found.”`;
In this case, why does it mean that the text is too long?

2022-06-12 12:57 UTC, pea3nut commented on src/extensions/ConflictFixer/index.ts
> +                    const eventsData = ud.map(ud => {
Why don't we use `this.conflicts.event_body.map` as the first layer so that we don't need to filter `.filter(Boolean)`

2022-06-12 12:57 UTC, pea3nut commented on src/extensions/ConflictFixer/index.ts
> +                if (filterData.length === 1) {
What's the logic behind this? Why does length being 1 mean description overlapping?

2022-06-12 12:57 UTC, pea3nut commented on src/extensions/ConflictFixer/index.ts
> +
Why did we put this logic under this condition when `DEBUG` is true

2022-06-12 12:57 UTC, pea3nut commented on src/extensions/ConflictFixer/index.ts
> +                        errorMsg = `${errorMsg} “Too close entry found for event.date”`;
Why does `dayDifference` being true mean "too close entry found for event.date"?

2022-06-12 12:57 UTC, pea3nut commented on src/extensions/ConflictFixer/index.ts
> +                    errorMsg = `${errorMsg} ${filterData.toString()}`;
Do you think that users would understand what the problem is when they saw this message?

2022-10-29 05:32 UTC, closed without merging